Spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://coke-database1.cgsjh8bmyvva.ap-northeast-2.rds.amazonaws.com:3306/webdb?serverTimezone=Asia/Seoul
    username: cokeAdmin
    password: wjdghks2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true